---
title: "R Notebook"
output: html_notebook
---

# **Modeled events**

A modeled event is a discontinuity introduced into the simulation at a time and with characteristics that are determined within the model itself, rather than the standard setup of specifying these events via the data set.

In this vignette, we\'ll focus on creating a discontinuity in the simulation so that the value of a parameter can change at a specific time that is not necessarily chosen prior to the run time.

# **Concept: mevent**

This toy model shows how you can use `mevent()` to schedule a discontinuity into the simulation. This model doesn\'t do anything, but will help us see what parts are in play.

``` cpp
[ MAIN ]

// Part A
if(NEWIND <=1) double mtime = 1E10;

// Part B
if(EVID==1) {
  mtime = TIME + 1.23;
  self.mevent(mtime, 33);
}

// Part C
capture past  = TIME >= mtime;
```

In contrast to the NONMEM `MTIME()` functionality, we have to do a little more work keeping track of the status of the system. There are multiple ways to organize this. I\'m going to show you one way that tries to minimize the amount of this book keeping work.

In the first part of `[ MAIN ]`, I will create a variable called `mtime` and initialize it to some large, arbitrary value. This is the time of the modeled event and we will eventually want to check to see if we are past this time. Initializing to this large .value will ensure we aren\'t past `mtime` when the problem starts. This is Part A.

```{r}
plot(cars)
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Cmd+Option+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Cmd+Shift+K* to preview the HTML file).

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.
